PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://www.smartcity.madrid.es/mobility/ontology/>
PREFIX mty: <http://www.smartcity.madrid.es/mobility/>
@prefix owl: <http://www.w3.org/2002/07/owl#>.

SELECT DISTINCT ?b
WHERE{
    ?b rdf:type dbo:Bus.
    ?b dbo:Ward_Name "Embajadores". 
    ?b dbo:District_Name "Centro". 
    ?b dbo:Bus_Lines "T32".
}

SELECT DISTINCT ?metrostation
WHERE{
    ?metrostation rdf:type dbo:Metro.
    ?metrostation dbo:Ward_Name "Embajadores". 
}

SELECT DISTINCT ?dis
WHERE{
    ?dis rdf:type dbo:Wards.
    ?dis dbo:hasMetro "EMBAJADORES". 
}

SELECT DISTINCT ?d
WHERE{
    ?d rdf:type dbo:Bus.
    ?d owl:sameAs <https://wikidata.org/entity/Q1763376>.
}

SELECT DISTINCT ?MetroLigero ?MetroLigeroW
WHERE{
    ?MetroLigero rdf:type dbo:LightMetro.
    ?MetroLigero owl:sameAs ?MetroLigeroW    
} LIMIT 10;