PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?district

    WHERE {
        ?district rdf:type <http://parquimetrosdemadrid.com/District>.
        ?district owl:sameAs <https://www.wikidata.org/wiki/Q1763376>.
    }


SELECT COUNT (?neighborhood) as ?numBarrioPalacio
    WHERE {
        ?neighborhood rdf:type <http://parquimetrosdemadrid.com/Neighborhood>.
        ?neighborhood owl:sameAs <https://wikidata.org/entity/Q2136510>.
    }
