PREFIX admingeo: <http://data.ordnancesurvey.co.uk/ontology/admingeo/>
PREFIX dc: <https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#>
PREFIX ns:  <http://smartcity.linkeddata.es/ontology/TerrazasMadrid/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX sosa: <https://www.w3.org/TR/vocab-ssn/#SOSA>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>



#Devuelve todos los distritos contenidos en el csv.
SELECT ?district
WHERE{
    ?district rdf:type admingeo:District
}

#Devuelve todos los nombres y la direccion de los locales del distrito de Chamartín.
SELECT ?nombre ?direccion
WHERE{
    ?local rdf:type schema:LocalBusiness.
    ?local ns:containedIn ?neighborhood.
    ?neighborhood ns:locatedIn <http://smartcity.linkeddata.es/ontology/TerrazasMadrid/District/CHAMARTIN>.
    ?local dc:title ?nombre.
    ?local schema:address ?PostalAdress.
    ?PostalAdress schema:streetAddress ?direccion
}


#Devuelve el codigo postal del Local Cafeteria Parisiena.
SELECT ?local ?postalcode
WHERE{
    ?local dc:title "BAR HOGAR".
    ?local schema:address ?adress.
    ?adress schema:postalCode ?postalcode
}

#Devuelve el barrio en que se encuentra un local dado su ID.
SELECT ?neighborhood
WHERE{
    ?local ns:hasID "170000836"^^xsd:integer.
    ?local ns:containedIn ?neighborhood
}

#Devuelve las coordenadas de aquellos locales que se encuentran abiertos en Madrid

SELECT ?local ?Geocordinates
WHERE{
    ?local ns:status "Abierto".
    ?local ns:hasLocation ?Geo.
    ?Geo ns:GeoCoordinatesID ?Geocordinates
}


