PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbr: <http://www.banderasazulesgalicia.com#>
PREFIX res: <http://www.banderasazulesgalicia.com#>


#Query1
SELECT ?playa 
WHERE {
    ?playa rdf:type dbr:Tipo-de-Arena.
    ?playa dbr:TIPO-DE-ARENA "Gruesa"
}

#Query2
SELECT ?playa,?tipoPlaya
WHERE{
    ?playa,?tipoPlaya rdf:type dbr:Provincia.
    ?playa,?tipoPlaya dbr:CODIGO-PROVINCIA "27"
}

#Query3
SELECT ?tipoArena 
WHERE{
    ?tipoArena  rdf:type dbr:Playa.
    ?tipoArena  dbr:PLAYA "Sabon"
}