PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rc: <http://smartcity.smartbins.es/lcc/ontology/recycle#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
    
#QUERY 1: BINS

SELECT DISTINCT ?Bin ?link WHERE{
        ?Bin rdf:type rc:Bin.
        ?Bin owl:sameAs ?link.
    }

#http://smartcity.smartbins.es/lcc/resource/Bin/1523159		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523493		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523138		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523117		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523472		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523280		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523259		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523359		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1522416		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523004		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523188		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523167		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523317		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523125		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1521210		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523267		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523225		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522992		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523175		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523112		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523296		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523254		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523233		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1517391		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523183		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523162		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523504		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523141		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523496		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523120		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523262		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522987		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523007		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523512		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523149		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523128		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523483		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523228		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523207		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523199		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523178		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523520		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523328		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523115		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1522882		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522982		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523186		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523507		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523144		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523123		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523244		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523202		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523010		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523152		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523486		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523252		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1522998		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523210		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523352		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523502		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523139		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523118		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523473		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523260		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523239		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523218		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523360		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523510		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523168		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523147		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523481		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523247		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522993		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523155		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523113		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523276		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523255		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523234		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523213		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523000		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523184		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523163		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523505		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523142		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523121		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522846		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523221		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522988		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523008		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523513		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523129		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523292		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522996		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523208		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523521		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523158		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523329		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523492		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523308		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523116		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523279		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523216		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523003		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523187		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523508		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523479		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523224		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522991		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523195		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523516		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523466		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523253		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523211		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523182		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523140		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523119		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1522886		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523282		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523261		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523240		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522986		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523006		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523511		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523319		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523127		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523248		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1522994		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523198		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523519		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523135		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523114		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523298		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523256		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523235		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522981		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523356		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523185		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523164		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523506		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523143		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523122		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522889		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523285		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523243		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523222		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523201		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522989		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523009		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522968		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523193		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523130		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523485		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523293		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523464		https://wikidata.org/entity/Q1194111
#http://smartcity.smartbins.es/lcc/resource/Bin/1523230		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1522997		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523522		https://wikidata.org/entity/Q132580
#http://smartcity.smartbins.es/lcc/resource/Bin/1523501		https://wikidata.org/entity/Q132580

#QUERY 2: PRODUCTS

SELECT DISTINCT ?Product ?link WHERE{
        ?Product rdf:type rc:Product.
        ?Product owl:sameAs ?link.
    } ORDER BY asc(?Product)

#http://smartcity.smartbins.es/lcc/resource/Product/1		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/10		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/100		https://wikidata.org/entity/Q498439
#http://smartcity.smartbins.es/lcc/resource/Product/101		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/102		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/103		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/104		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/105		https://wikidata.org/entity/Q6432723
#http://smartcity.smartbins.es/lcc/resource/Product/106		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/107		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/108		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/109		https://wikidata.org/entity/Q81727
#http://smartcity.smartbins.es/lcc/resource/Product/11		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/110		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/111		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/112		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/113		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/114		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/115		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/116		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/117		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/118		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/119		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/12		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/120		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/121		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/122		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/123		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/124		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/125		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/126		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/127		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/128		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/129		https://wikidata.org/entity/Q959287
#http://smartcity.smartbins.es/lcc/resource/Product/13		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/130		https://wikidata.org/entity/Q959287
#http://smartcity.smartbins.es/lcc/resource/Product/131		https://wikidata.org/entity/Q959287
#http://smartcity.smartbins.es/lcc/resource/Product/132		https://wikidata.org/entity/Q959287
#http://smartcity.smartbins.es/lcc/resource/Product/133		https://wikidata.org/entity/Q189211
#http://smartcity.smartbins.es/lcc/resource/Product/134		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/135		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/14		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/15		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/16		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/17		https://wikidata.org/entity/Q104541
#http://smartcity.smartbins.es/lcc/resource/Product/18		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/19		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/2		https://wikidata.org/entity/Q3444710
#http://smartcity.smartbins.es/lcc/resource/Product/20		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/21		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/22		https://wikidata.org/entity/Q81727
#http://smartcity.smartbins.es/lcc/resource/Product/23		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/24		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/25		https://wikidata.org/entity/Q3360230
#http://smartcity.smartbins.es/lcc/resource/Product/26		https://wikidata.org/entity/Q3501372
#http://smartcity.smartbins.es/lcc/resource/Product/27		https://wikidata.org/entity/Q3501372
#http://smartcity.smartbins.es/lcc/resource/Product/28		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/283		https://wikidata.org/entity/Q1578
#http://smartcity.smartbins.es/lcc/resource/Product/284		https://wikidata.org/entity/Q1578
#http://smartcity.smartbins.es/lcc/resource/Product/285		https://wikidata.org/entity/Q1578
#http://smartcity.smartbins.es/lcc/resource/Product/29		https://wikidata.org/entity/Q4370258
#http://smartcity.smartbins.es/lcc/resource/Product/3		https://wikidata.org/entity/Q1413974
#http://smartcity.smartbins.es/lcc/resource/Product/30		https://wikidata.org/entity/Q1413974
#http://smartcity.smartbins.es/lcc/resource/Product/31		https://wikidata.org/entity/Q11474
#http://smartcity.smartbins.es/lcc/resource/Product/32		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/33		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/34		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/35		https://wikidata.org/entity/Q11301688
#http://smartcity.smartbins.es/lcc/resource/Product/36		https://wikidata.org/entity/Q11301688
#http://smartcity.smartbins.es/lcc/resource/Product/37		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/38		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/39		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/4		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/40		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/41		https://wikidata.org/entity/Q12360
#http://smartcity.smartbins.es/lcc/resource/Product/42		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/43		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/44		https://wikidata.org/entity/Q4370258
#http://smartcity.smartbins.es/lcc/resource/Product/45		https://wikidata.org/entity/Q2909236
#http://smartcity.smartbins.es/lcc/resource/Product/46		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/47		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/48		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/49		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/5		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/50		https://wikidata.org/entity/Q104541
#http://smartcity.smartbins.es/lcc/resource/Product/51		https://wikidata.org/entity/Q6432723
#http://smartcity.smartbins.es/lcc/resource/Product/52		https://wikidata.org/entity/Q1131992
#http://smartcity.smartbins.es/lcc/resource/Product/53		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/54		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/55		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/56		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/57		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/58		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/59		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/6		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/60		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/61		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/62		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/63		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/64		https://wikidata.org/entity/Q104541
#http://smartcity.smartbins.es/lcc/resource/Product/65		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/66		https://wikidata.org/entity/Q1334994
#http://smartcity.smartbins.es/lcc/resource/Product/67		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/68		https://wikidata.org/entity/Q104541
#http://smartcity.smartbins.es/lcc/resource/Product/69		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/7		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/70		https://wikidata.org/entity/Q3360230
#http://smartcity.smartbins.es/lcc/resource/Product/71		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/72		https://wikidata.org/entity/Q3360230
#http://smartcity.smartbins.es/lcc/resource/Product/73		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/74		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/75		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/76		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/77		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/78		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/79		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/8		https://wikidata.org/entity/Q1440281
#http://smartcity.smartbins.es/lcc/resource/Product/80		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/81		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/82		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/83		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/84		https://wikidata.org/entity/Q2909236
#http://smartcity.smartbins.es/lcc/resource/Product/85		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/86		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/87		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/88		https://wikidata.org/entity/Q1072971
#http://smartcity.smartbins.es/lcc/resource/Product/89		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/9		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/90		https://wikidata.org/entity/Q2488579
#http://smartcity.smartbins.es/lcc/resource/Product/91		https://wikidata.org/entity/Q3261783
#http://smartcity.smartbins.es/lcc/resource/Product/92		https://wikidata.org/entity/Q1196111
#http://smartcity.smartbins.es/lcc/resource/Product/93		https://wikidata.org/entity/Q104541
#http://smartcity.smartbins.es/lcc/resource/Product/94		https://wikidata.org/entity/Q6432723
#http://smartcity.smartbins.es/lcc/resource/Product/95		https://wikidata.org/entity/Q1471060
#http://smartcity.smartbins.es/lcc/resource/Product/96		https://wikidata.org/entity/Q5840
#http://smartcity.smartbins.es/lcc/resource/Product/97		https://wikidata.org/entity/Q1757946
#http://smartcity.smartbins.es/lcc/resource/Product/98		https://wikidata.org/entity/Q5567094
#http://smartcity.smartbins.es/lcc/resource/Product/99		https://wikidata.org/entity/Q4370258